### ISSUE TITLE
Problema no install e start

### ISSUE THREAD

**Issue by devinvestidor** [m4rciosouza/kz-angular2-webpack-template#8]
Ao executar o npm install o seguinte retorno é apresentado:

```
> angular-quickstart@1.0.0 postinstall D:\Desenvolvimento\git\kz-angular2-webpack-template
> typings install

typings WARN deprecated 2016-10-25: "registry:dt/jasmine#2.2.0+20160621224255" is deprecated (updated, replaced or removed)
typings WARN deprecated 2016-11-21: "registry:dt/node#6.0.0+20160807145350" is deprecated (updated, replaced or removed)

+-- jasmine (global)
`-- node (global)

npm WARN angular-quickstart@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 9.626s
```

Ao executar o npm start:

```
> angular-quickstart@1.0.0 start D:\Desenvolvimento\git\kz-angular2-webpack-template
> webpack-dev-server --inline --progress --port 8080
                                                                                                                                      70% 3/3 build modulesevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1338:19)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-quickstart@1.0.0 start: `webpack-dev-server --inline --progress --port 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Apollus\AppData\Roaming\npm-cache\_logs\2018-08-01T13_32_51_706Z-debug.log
```

**Comment by devinvestidor** [comment]
No meu caso a porta 8080 já estava sendo utilizada, por isso a mensagem. Para resolver o problema alterei a porta para 8082 nos seguintes arquivos:

> webpack.dev.js
> package.json
> protractor.config.js
> crud-script.js
